import { useEffect, useState } from 'react';
import { Link } from "react-router-dom";
import { PlusCircle, Code, Github } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

// Type definition for artifacts
interface Artifact {
  id: string;
  name: string;
  description: string;
  path: string;
  built_in: boolean;
  created_at?: string;
}

const Home = () => {
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // Fetch artifacts from the server
  useEffect(() => {
    const fetchArtifacts = async () => {
      setLoading(true);
      try {
        const response = await fetch('/api/artifacts');
        if (!response.ok) {
          throw new Error(`Server responded with ${response.status}`);
        }
        const data = await response.json();
        
        if (data && data.artifacts) {
          setArtifacts(data.artifacts);
        } else {
          setArtifacts([]);
        }
      } catch (error) {
        console.error('Error fetching artifacts:', error);
        setError('Failed to load artifacts. Please try again later.');
        
        // Fallback to built-in artifacts
        setArtifacts([
          {
            id: 'login',
            name: 'Login Form',
            description: 'A simple login form with email and password fields',
            path: '/',
            built_in: true
          },
          {
            id: 'signup',
            name: 'Sign Up Form',
            description: 'A registration form with validation and social sign-up options',
            path: '/signup',
            built_in: true
          }
        ]);
      } finally {
        setLoading(false);
      }
    };
    fetchArtifacts();
  }, []);

  return (
    <div className="bg-gray-100 min-h-screen p-6">
      <div className="max-w-7xl mx-auto">
        <header className="mb-8 text-center">
          <h1 className="text-3xl font-bold mb-2">Claude Artifact Runner</h1>
          <p className="text-gray-600 mb-4">
            Preview and test components generated by Claude
          </p>
          <div className="flex justify-center space-x-3">
            <Button asChild variant="default" className="flex items-center gap-2">
              <Link to="/paste">
                <PlusCircle className="h-4 w-4" />
                Paste New Artifact
              </Link>
            </Button>
            <Button asChild variant="outline" className="flex items-center gap-2">
              <a href="https://github.com/claudio-silva/claude-artifact-runner" target="_blank" rel="noopener noreferrer">
                <Github className="h-4 w-4" />
                GitHub
              </a>
            </Button>
          </div>
        </header>

        {error && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-md text-red-700">
            {error}
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {artifacts.map((artifact) => (
            <Card key={artifact.id} className="overflow-hidden">
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2">
                  {artifact.name}
                  {artifact.built_in && (
                    <span className="px-2 py-1 text-xs bg-blue-100 text-blue-700 rounded-full">Built-in</span>
                  )}
                </CardTitle>
                <CardDescription>{artifact.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-40 bg-gray-200 rounded-md flex items-center justify-center">
                  <Code className="h-10 w-10 text-gray-400" />
                </div>
              </CardContent>
              <CardFooter className="bg-gray-50 border-t">
                <Button asChild variant="default" className="w-full">
                  <Link to={artifact.path}>
                    View Artifact
                  </Link>
                </Button>
              </CardFooter>
            </Card>
          ))}

          {artifacts.length === 0 && !loading && (
            <div className="col-span-full text-center p-6 bg-white rounded-md border">
              <Code className="h-12 w-12 text-gray-400 mx-auto mb-2" />
              <h3 className="text-lg font-medium mb-1">No artifacts found</h3>
              <p className="text-gray-500 mb-4">Start by pasting a new artifact from Claude.</p>
              <Button asChild>
                <Link to="/paste">
                  <PlusCircle className="h-4 w-4 mr-2" />
                  Paste New Artifact
                </Link>
              </Button>
            </div>
          )}

          {loading && (
            <div className="col-span-full text-center py-12">
              <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full mx-auto mb-4"></div>
              <p className="text-gray-500">Loading artifacts...</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Home;